"""Selenium script generation using LangChain and Gemini."""
from typing import Dict, List
import json
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.prompts import PromptTemplate
from backend.settings import settings
from backend.models import TestCase
from backend.utils import get_logger

logger = get_logger(__name__)


# Selenium Script Generation Prompt Template
SELENIUM_GENERATION_TEMPLATE = """SYSTEM:
You are a senior Selenium Python engineer.
Generate a fully executable Python script implementing the provided test case.
Use ONLY selectors available in selector_map.
If a selector is missing, insert a TODO comment and print "SKIP: Missing selector for [element]" and exit the script early.
Use WebDriverWait and assert statements.
Output Python code only. No commentary or markdown formatting.

USER:
Test Case:
{test_case_json}

Selector Map:
{selector_map_json}

Support Evidence:
{support_evidence}

INSTRUCTIONS:
- Use BASE_URL as a placeholder (set to "file:///path/to/checkout.html" or similar)
- Import required Selenium modules: webdriver, By, WebDriverWait, expected_conditions
- Use strict waits with WebDriverWait (timeout=10)
- Add assertions for Expected_Result validation
- Use only selectors from the selector_map
- If a required selector is missing, output: print("SKIP: Missing selector for [element_name]") and sys.exit(0)
- If Expected_Result cannot be validated due to missing evidence, add comment: # TODO: Validation requires additional evidence
- Use try-except blocks for error handling
- Add cleanup: driver.quit() in finally block
- Output ONLY Python code, no markdown code blocks, no explanations

Generate the complete Selenium script now:"""


class SeleniumScriptGenerator:
    """Generate Selenium scripts from test cases."""
    
    def __init__(self):
        """Initialize Selenium script generator."""
        self.llm = ChatGoogleGenerativeAI(
            model=settings.LLM_MODEL,
            temperature=0.0,  # Zero temperature for deterministic code generation
            max_output_tokens=settings.LLM_MAX_OUTPUT_TOKENS,
            google_api_key=settings.GOOGLE_API_KEY
        )
        
        self.prompt_template = PromptTemplate(
            template=SELENIUM_GENERATION_TEMPLATE,
            input_variables=["test_case_json", "selector_map_json", "support_evidence"]
        )
    
    def generate_script(
        self,
        test_case: TestCase,
        selector_map: Dict[str, str],
        support_evidence: str = ""
    ) -> Dict:
        """
        Generate Selenium script from test case.
        
        Args:
            test_case: TestCase object
            selector_map: Dictionary mapping element descriptions to CSS selectors
            support_evidence: Supporting documentation snippets
            
        Returns:
            Dictionary with status, script, and missing selectors
        """
        try:
            # Check for required selectors
            missing_selectors = []
            for selector_needed in test_case.SelectorsNeeded:
                found = False
                for key in selector_map.keys():
                    if selector_needed.lower() in key.lower():
                        found = True
                        break
                if not found:
                    missing_selectors.append(selector_needed)
            
            # Prepare test case JSON
            test_case_json = json.dumps(test_case.model_dump(), indent=2)
            
            # Prepare selector map JSON
            selector_map_json = json.dumps(selector_map, indent=2)
            
            # Create prompt
            prompt = self.prompt_template.format(
                test_case_json=test_case_json,
                selector_map_json=selector_map_json,
                support_evidence=support_evidence or "No additional support evidence provided"
            )
            
            # Generate script
            logger.info(f"Generating Selenium script for test case: {test_case.Test_ID}")
            response = self.llm.invoke(prompt)
            
            # Extract script from response
            script = response.content.strip()
            
            # Remove markdown code blocks if present
            if "```python" in script:
                script = script.split("```python")[1].split("```")[0].strip()
            elif "```" in script:
                script = script.split("```")[1].split("```")[0].strip()
            
            # Add header comment
            header = f"""#!/usr/bin/env python3
\"\"\"
Selenium Test Script
Test ID: {test_case.Test_ID}
Feature: {test_case.Feature}
Test Scenario: {test_case.Test_Scenario}
Test Type: {test_case.Test_Type}

Auto-generated by Autonomous QA Agent
\"\"\"

"""
            
            script = header + script
            
            # Validate script has required imports
            if "from selenium" not in script and "import selenium" not in script:
                script = """import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException

""" + script
            
            return {
                "status": "ok",
                "script": script,
                "missing_selectors": missing_selectors
            }
            
        except Exception as e:
            logger.error(f"Error generating Selenium script: {e}")
            return {
                "status": "error",
                "script": f"# Error generating script: {str(e)}",
                "missing_selectors": missing_selectors
            }
    
    def generate_script_template(self, test_case: TestCase) -> str:
        """
        Generate a basic script template when full generation fails.
        
        Args:
            test_case: TestCase object
            
        Returns:
            Template script as string
        """
        template = f'''#!/usr/bin/env python3
"""
Selenium Test Script Template
Test ID: {test_case.Test_ID}
Feature: {test_case.Feature}
Test Scenario: {test_case.Test_Scenario}
"""

import sys
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# Configuration
BASE_URL = "file:///path/to/checkout.html"
TIMEOUT = 10

def test_{test_case.Test_ID.lower().replace("-", "_")}():
    """
    {test_case.Test_Scenario}
    
    Preconditions:
{chr(10).join(f"    - {p}" for p in test_case.Preconditions)}
    
    Expected Result:
    {test_case.Expected_Result}
    """
    driver = None
    
    try:
        # Setup
        driver = webdriver.Chrome()
        driver.get(BASE_URL)
        wait = WebDriverWait(driver, TIMEOUT)
        
        # Test Steps:
{chr(10).join(f"        # Step {i+1}: {step}" for i, step in enumerate(test_case.Steps))}
        
        # TODO: Implement test steps using selectors
        # TODO: Add assertions for expected results
        
        print(f"Test {test_case.Test_ID} - PASSED")
        
    except Exception as e:
        print(f"Test {test_case.Test_ID} - FAILED: {{e}}")
        raise
        
    finally:
        if driver:
            driver.quit()


if __name__ == "__main__":
    test_{test_case.Test_ID.lower().replace("-", "_")}()
'''
        return template
